import json
from typing import Union
import pathlib

class QuestionnaireAnalysis:
    """
    Reads and analyzes data generated by the questionnaire experiment.
    Should be able to accept strings and pathlib.Path objects.
    """
    
    def __init__(self, data_fname: Union[pathlib.Path, str]):
        self.data_fname = data_fname
        self.data = None

    def read_data(self):
        """
        Reads the json data located in self.data_fname into memory, to
        the attribute self.data.
        """
        with open(self.data_fname, encoding='utf-8') as f:
            self.data = json.loads(f.read())


if __name__ == "__main__":
    data_fname = 'data.json'
    d = QuestionnaireAnalysis(data_fname)
    d.read_data()
    print (d.data)
        
        
